/** route for second page */
export const SECOND_PAGE: string = 'pages/VideoPlayerPage'

/** route param */
export const SOURCE: string = 'source'

/** video net address */
export const NET_VIDEO_URL: string =
'https://vdept3.bdstatic.com/mda-qff32rf9ks0vrnc7/sc/cae_h264/1718503908257507831/mda-qff32rf9ks0vrnc7.mp4?v_from_s=hkapp-haokan-hbe&auth_key=1721226463-0-0-4852ee8ea3e8854a15b5d8d0fae85e45&bcevod_channel=searchbox_feed&cr=2&cd=0&pd=1&pt=3&logid=1663499192&vid=11346306773522438905&klogid=1663499192&abtest=101830_1-17451_1-3000225_3'
/** toast message */
export const MESSAGE: string = '请检查网络'

/** init time of string */
export const START_TIME: string = '00:00'

/** Zero */
export const ZERO_STR = '0'

/** time splite */
export const TIME_SPLIT: string = ':'

/** default opacity */
export const DEFAULT_OPACITY: number = 0.2 // Number.parseFloat('0.2')

/**
 * slider small track thick ness
 */
export const SMALL_TRACK_THICK_NESS: number = 2;

/**
 * slider big track thick ness
 */
export const BIG_TRACK_THICK_NESS: number = 4;

/**
 * the divide of single and double
 */
export const COMMON_NUM_DOUBLE: number = 10;

/**
 * the minute of one hour
 */
export const COMMON_NUM_MINUTE: number = 60;

/**
 * common font weight
 */
export const COMMON_NUM_FONT_WEIGHT: number = 500;

/**
 * toast duration
 */
export const COMMON_NUM_DURATION: number = 5000;

/**
 * module list
 */
export const LIST: string[] = ['最近播放', '为你推荐'];

/**
 * full percent
 */
export const ALL_PERCENT: string = '100%';

/**
 * Image Size
 */
export const IMAGE_SIZE: number = 24;

/**
 * component with or height percent
 */
export const enum STRING_PERCENT {
  SLIDER_WITH = '46.7%',
  NINETY_PERCENT = '88%',
  INDEX_COMPONENT_WITH_PERCENT = '93.3%',
  INDEX_SWIPER_HEIGHT_PERCENT = '24.1%',
  INDEX_MODULE_HEIGHT_PERCENT = '22.8%',
  INDEX_SWIPER_LEFT_RIGHT_MARGIN = '3.3%'
}

/**
 * margin or font size
 */
export const enum MARGIN_FONT_SIZE {
  FIRST_MARGIN = 12,
  SECOND_MARGIN = 16,
  THIRD_MARGIN = 18,
  FOURTH_MARGIN = 24,
  FIFTH_MARGIN = 50,
  SIXTH_MARGIN = 94,
  SEVENTH_MARGIN = 132
}

/**
 * video resource type
 */
export const enum VIDEO_TYPE {
  INNER = 'inner',
  NET = 'net'
}

/**
 * Attribute Styles in a Stack Layout
 */
export const enum STACK_STYLE {
  IMAGE_Z_INDEX = 2,
  PROGRESS_VALUE = 0,
  PROGRESS_TOTAL = 100,
  PROGRESS_STROKE_WIDTH = 15,
  PROGRESS_SCALE_COUNT = 15,
  PROGRESS_SCALE_WIDTH = 5,
  PROGRESS_Z_INDEX = 1,
  PROGRESS_WIDTH = 80,
  PROGRESS_STEP = 10,
  MILLI_SECONDS = 100
}

