/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { webview } from '@kit.ArkWeb';
import { contact } from '@kit.ContactsKit';
import { code } from '../constant/CodeConstant';
import { ParamsItem as ParamsItem } from '../../viewmodel/ParamsItem';
import { JavaScriptItem } from '../../viewmodel/JavaScriptItem';
import Logger from './JsLogger';

/**
 * Define bridge class connect WebView and ArkTS.
 */
export default class JsBridge {
  controller: webview.WebviewController;

  constructor(controller: webview.WebviewController) {
    this.controller = controller;
  }

  /**
   * Injects the JavaScript object into window and invoke the function in window.
   *
   * @returns javaScriptProxy object.
   */
  get javaScriptProxy(): JavaScriptItem {
    let result: JavaScriptItem = {
      object: {
        call: this.call
      },
      name: 'JSBridgeHandle',
      methodList: ['call'],
      controller: this.controller
    }
    return result;
  }

  /**
   * initialize the bridge.
   */
  initJsBridge(): void {
    this.controller.runJavaScript(code);
  }

  /**
   * Use system ability of getting contacts.
   */
  chooseContact = (): Promise<string> => {
    let phone = '';
    let name = '';
    return new Promise((resolve) => {
      let promise = contact.selectContacts();
      promise.then((info: Array<contact.Contact>) => {
        info.forEach((item: contact.Contact) => {
          phone = item?.phoneNumbers ? item?.phoneNumbers[0].phoneNumber : '';
          name = item?.name ? item?.name?.fullName : '';
        })
        resolve(phone + '_' + name);
      }).catch((err: object | string) => {
        Logger.error(`selectContact fail: err->${JSON.stringify(err)}`);
      });
    })
  }

  /**
   * Change tel function.
   */
  changeTel = (params: ParamsItem): Promise<string> => {
    Logger.info('手机号', JSON.stringify(params));
    const tel: string = params.data.tel ?? '';
    AppStorage.set<string>('tel', tel);
    return new Promise((resolve) => {
      resolve('success');
    })
  }

  /**
   * Change amount function.
   */
  changeAmount = (): Promise<string> => {
    AppStorage.set<boolean>('isClick', true);
    return new Promise((resolve) => {
      resolve('success');
    })
  }

  /**
   * Compatible with different dpi.
   */
  getProportion = (): Promise<string> => {
    return new Promise((resolve) => {
      resolve(String(AppStorage.get<number>('proportion')));
    })
  }

  /**
   * Invoke the chooseContact function.
   */
  call = (func: string, params: string): void => {
    const paramsObject: ParamsItem = JSON.parse(params);
    let result: Promise<string> = new Promise((resolve) => resolve(''));
    switch (func) {
      case 'chooseContact':
        result = this.chooseContact();
        break;
      case 'changeTel':
        result = this.changeTel(paramsObject);
        break;
      case 'changeAmount':
        result = this.changeAmount();
        break;
      case 'getProportion':
        result = this.getProportion();
        break;
      default:
        break;
    }
    result.then((data: string) => {
      this.callback(paramsObject?.callID, data);
    })
  }

  /**
   * The ArkTS invoke the WebView by using runJavaScript.
   */
  callback = (id: number, data: string): void => {
    this.controller.runJavaScript(`JSBridgeCallback('${id}', ${JSON.stringify(data)})`);
  }
}